### ISSUE TITLE
Output Alignment naming

### ISSUE THREAD

**Issue by Gnmerich** [eggzilla/SelectSequencesFromMSA#2]
Currently the selected Alignment is output as follows:

- As **results.selected** in the _working directory_ OR
- As **results.selected** in the _directory specified with the -o option_

It would be rather helpful if the actual name of the output file could be specified, or is in some way related to the input file name. Since any existing results.selected is overwritten, running the program multiple times in one directory could potentially lead to unwanted loss of data.

**Comment by eggzilla** [comment]
@Gnmerich Thanks for reporting the issue. The output filename can now be set via the -f commandline
parameter. Please check and close the issue.
