### ISSUE TITLE
Cannot parse alignment with empty lines near EOF

### ISSUE THREAD

**Issue by Gnmerich** [eggzilla/SelectSequencesFromMSA#3]
When parsing attached alignment [930881.aln.txt](https://github.com/eggzilla/SelectSequencesFromMSA/files/1792754/930881.aln.txt) (written by Biopythons AlignIO), following Error occurs:

**"A problem occured selecting sequences: \"930881.aln\" (line 5018, column 1):\nunexpected '\\n'\nexpecting end of input"**

The Problem seems to come from the last (empty) line, since its removal also fixes the problem.

**Comment by eggzilla** [comment]
@Gnmerich Thanks for reporting the issue. It should be fixed in 1.0.5, please check and close the ticket if it works.

**Comment by eggzilla** [comment]
Ping @Gnmerich
